-- ============================================================
-- Migration 002 — Primary pipeline tables
-- Version: 1.0 | March 2026
-- ============================================================
-- up

-- Raw JSON snapshots from the primary API pipeline
CREATE TABLE IF NOT EXISTS menu_snapshots (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  competitor_id   UUID REFERENCES competitors(id) ON DELETE CASCADE,
  slug            TEXT NOT NULL,
  snapshot_json   JSONB NOT NULL,
  item_count      INT DEFAULT 0,
  pages_fetched   INT DEFAULT 0,
  collected_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_menu_snapshots_competitor
  ON menu_snapshots(competitor_id, collected_at DESC);

-- Normalized menu items (one row per SKU per collection run)
CREATE TABLE IF NOT EXISTS menu_items (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  snapshot_id         UUID REFERENCES menu_snapshots(id) ON DELETE CASCADE,
  competitor_id       UUID REFERENCES competitors(id) ON DELETE CASCADE,
  platform_item_id    TEXT,
  name                TEXT NOT NULL,
  brand               TEXT,
  category            TEXT,
  subcategory         TEXT,
  price               DECIMAL(8,2),
  original_price      DECIMAL(8,2),
  on_sale             BOOLEAN DEFAULT FALSE,
  discount_label      TEXT,
  current_deal_title  TEXT,
  deal_ids            TEXT[],
  thc_mg              DECIMAL(8,2),
  cbd_mg              DECIMAL(8,2),
  genetics_tag        TEXT,
  strain_name         TEXT,
  is_online_orderable BOOLEAN DEFAULT TRUE,
  updated_at          TIMESTAMPTZ,
  collected_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_menu_items_competitor
  ON menu_items(competitor_id, collected_at DESC);
CREATE INDEX IF NOT EXISTS idx_menu_items_snapshot
  ON menu_items(snapshot_id);
CREATE INDEX IF NOT EXISTS idx_menu_items_platform_id
  ON menu_items(competitor_id, platform_item_id);

-- Pipeline health / run metadata
CREATE TABLE IF NOT EXISTS pipeline_health (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_date              DATE NOT NULL DEFAULT CURRENT_DATE,
  total_attempted       INT DEFAULT 0,
  total_succeeded       INT DEFAULT 0,
  total_failed          INT DEFAULT 0,
  avg_response_time_ms  DECIMAL(10,2),
  ip_pool_status        JSONB,
  errors                JSONB,
  started_at            TIMESTAMPTZ DEFAULT NOW(),
  completed_at          TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_pipeline_health_date
  ON pipeline_health(run_date DESC);

-- Change events generated by diff_engine
CREATE TABLE IF NOT EXISTS change_events (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  competitor_id   UUID REFERENCES competitors(id) ON DELETE CASCADE,
  event_type      TEXT NOT NULL,
  platform_item_id TEXT,
  item_name       TEXT,
  brand           TEXT,
  category        TEXT,
  old_value       JSONB,
  new_value       JSONB,
  detected_at     TIMESTAMPTZ DEFAULT NOW(),
  processed       BOOLEAN DEFAULT FALSE,
  processed_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_change_events_competitor
  ON change_events(competitor_id, detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_change_events_unprocessed
  ON change_events(processed) WHERE processed = FALSE;

-- down
-- DROP TABLE IF EXISTS change_events;
-- DROP TABLE IF EXISTS pipeline_health;
-- DROP TABLE IF EXISTS menu_items;
-- DROP TABLE IF EXISTS menu_snapshots;
